apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: minhaz71/react-app-aws-eks:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: http://a293d8856357f4a7581a41e00f12dd4a-1698539534.ap-southeast-1.elb.amazonaws.com:5000

---
apiVersion: v1
kind: Service
metadata:
  name: react-app
spec:
  type: LoadBalancer
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000



