# name: Build and Push Docker Images

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'
#       - 'backend/**'
#   pull_request:
#     branches:
#       - main
#     paths:
#       - 'frontend/**'
#       - 'backend/**'

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     env:
#       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # Fetch all history for all branches and tags

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Check for frontend and backend changes
#         id: changes
#         run: |
#           git fetch origin main

#           # Determine the base commit
#           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
#             BASE_COMMIT=${{ github.event.pull_request.base.sha }}
#           else
#             BASE_COMMIT=$(git rev-parse origin/main)
#           fi

#           # Check if frontend changed
#           if git diff --name-only $BASE_COMMIT HEAD | grep '^frontend/' > /dev/null; then
#             echo "frontend_changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "frontend_changed=false" >> $GITHUB_OUTPUT
#           fi

#           # Check if backend changed
#           if git diff --name-only $BASE_COMMIT HEAD | grep '^backend/' > /dev/null; then
#             echo "backend_changed=true" >> $GITHUB_OUTPUT
#           else
#             echo "backend_changed=false" >> $GITHUB_OUTPUT
#           fi

#       - name: Build and Push Docker Images
#         run: |
#           if [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" && "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
#             echo "Both frontend and backend have changed, running 'make all'."
#             make all
#           elif [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" ]]; then
#             echo "Frontend has changed, running 'make all-frontend'."
#             make all-frontend
#           elif [[ "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
#             echo "Backend has changed, running 'make all-backend'."
#             make all-backend
#           else
#             echo "No changes detected in frontend or backend."
#           fi

#       - name: Debug Information
#         run: |
#           echo "Event name: ${{ github.event_name }}"
#           echo "Base commit: $BASE_COMMIT"
#           echo "Current commit: ${{ github.sha }}"
#           echo "Changed files:"
#           git diff --name-only $BASE_COMMIT ${{ github.sha }}
name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Previous commit SHA: ${{ github.event.before }}"
          echo "Changed files:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Check for frontend and backend changes
        id: changes
        run: |
          echo "Checking for changes..."
          
          # Check if frontend changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/' > /dev/null; then
            echo "Frontend changes detected"
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No frontend changes detected"
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi

          # Check if backend changed
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/' > /dev/null; then
            echo "Backend changes detected"
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No backend changes detected"
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Images
        run: |
          if [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" && "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
            echo "Both frontend and backend have changed, running 'make all'."
            make all
          elif [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" ]]; then
            echo "Frontend has changed, running 'make all-frontend'."
            make all-frontend
          elif [[ "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
            echo "Backend has changed, running 'make all-backend'."
            make all-backend
          else
            echo "No changes detected in frontend or backend."
          fi