name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check for frontend and backend changes
        id: changes
        run: |
          git fetch origin main
          
          # Check if frontend changed
          if git diff --name-only origin/main..HEAD | grep '^frontend/' > /dev/null; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi

          # Check if backend changed
          if git diff --name-only origin/main..HEAD | grep '^backend/' > /dev/null; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and Push Docker Images
        run: |
          if [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" && "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
            echo "Both frontend and backend have changed, running 'make all'."
            make all
          elif [[ "${{ steps.changes.outputs.frontend_changed }}" == "true" ]]; then
            echo "Frontend has changed, running 'make all-frontend'."
            make all-frontend
          elif [[ "${{ steps.changes.outputs.backend_changed }}" == "true" ]]; then
            echo "Backend has changed, running 'make all-backend'."
            make all-backend
          else
            echo "No changes detected in frontend or backend."
          fi